name: holiday_lodges
description: HolidayLodges Mobile Application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.3.0
  cupertino_icons: ^1.0.2
  webview_flutter: ^3.0.0
  flutter_native_splash: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image.png"

flutter:
  uses-material-design: true
  assets:
    - assets/